name: C_build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ls -a
      run: |
        echo --------------------------
        ls -a
        echo --------------------------
    - name: run ./autogen.sh
      run: ./autogen.sh
    - name: ls -a
      run: |
        echo --------------------------
        ls -a
        echo --------------------------
