name: C_build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ls -la
      run: |
        echo --------------------------
        ls -la
        echo --------------------------
    - name: sudo apt update
      run: sudo apt update
    - name: apt install
      run: |
        sudo apt install libtool intltool autoconf automake libcurl4-openssl-dev
        sudo apt install pkg-config libglib2.0-dev libgtk-3-dev libgoocanvas-2.0-dev
    - name: run ./autogen.sh
      run: ./autogen.sh
    - name: create folder "build"
      run: |
        mkdir build
        cd ./build
        pwd
    # так как в скрипте выше нет команды "./configure", то вызываем её сами
    - name: ../configure
      run: ../configure 
    - name: ls -la
      run: |
        echo ls -la--------------------------
        ls -la
        echo --------------------------
        echo ls -la ./build--------------------------
        ls -la ./build
        echo ------------------------
    - name: ../make
      run:  ../make
    - name: ls -la
      run: |
        echo ls -la--------------------------
        ls -la
        echo --------------------------
        echo ls -la ./build--------------------------
        ls -la ./build
        echo ------------------------
    - name: tree -a
      run: |
        echo --------------------------
        tree -a
        echo --------------------------
